group:
  # name: Bed Lights Strip  
  cradlelights:
    - light.cradlelights
    - input_number.cradleLights_strip_speed  
    - input_number.cradlelights_brightness_slider
    - binary_sensor.cradleLights_motion
    - input_number.cradlelights_timer_slider
    - automation.cradleLights_auto_on
    - automation.cradleLights_auto_off
    - automation.cradleLights_effect_speed
    - timer.cradlelights

timer:
  cradlelights:
    name: cradlelights Timer
    icon: 'mdi:close-circle'

input_number:
  cradlelights_timer_slider:
    icon: mdi:timer
    name: cradleLights_timer
    initial: 30
    min: 1
    max: 600
    step: 10
    mode: slider
    unit_of_measurement: Seconds
  
  cradlelights_brightness_slider:
    icon: mdi:brightness-6
    name: cradleLights_brightness
    initial: 50
    min: 0
    max: 255
    step: 5
    mode: slider

automation:
  - alias: "cradlelights Auto On"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.cradleLights_motion
        to: 'on'
    action:
      - service: mqtt.publish
        data_template:
          topic: "cradlelights/light/cradlelights/state"
          payload: '{"effect":"None","state":"ON","brightness":{{ states.input_number.cradlelights_brightness_slider.state | int }},"color":{"r":255,"g":235,"b":181}}'
      - service: mqtt.publish
        data_template:
          topic: "cradlelights/light/cradlelights/command"
          payload: '{"state":"ON"}'
      - service: timer.start
        data_template:
          entity_id: timer.cradlelights
          duration: '00:00:{{ states.input_number.cradlelights_timer_slider.state | int }}' 
                    
  - alias: "cradlelights Auto Off"
    initial_state: True
    hide_entity: False
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.cradlelights
    action:
      - service: mqtt.publish
        data_template:
          topic: "cradlelights/light/cradlelights/state"                    
          payload: '{"effect":"None","state":"OFF","brightness":{{ states.input_number.cradlelights_brightness_slider.state | int }},"color":{"r":255,"g":235,"b":181}}'
      - service: mqtt.publish
        data_template:
          topic: "cradlelights/light/cradlelights/command"
          payload: '{"state":"OFF"}'

 