homeassistant: !include config/core/homeassistant.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password 
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

automation: !include_dir_merge_list config/automation
group: !include_dir_named config/groups
sensor: !include_dir_merge_list config/devices/sensors
switch: !include_dir_merge_list config/devices/switches
device_tracker: !include config/devices/device_tracker.yaml
xiaomi: !include config/devices/xiaomi.yaml

vacuum: !include config/devices/vacuum.yaml
#
