- platform: ffmpeg_noise
  name: ffmpeg_noise_miFang2
  input: rtsp://mifang2/unicast
  extra_arguments: -filter:a highpass=f=300,lowpass=f=2500,volume=volume=2 -codec:a libmp3lame -ar 16000
#  output: -f mp3 icecast://stream_user:stream_pw@127.0.0.1:8000/babyphone.mp3
  initial_state: false
  duration: 2
  reset: 60
  peak: -32