- name: floorplan
  sidebar_title: Floorplan
  sidebar_icon: mdi:home
  url_path: floorplan
  config:
    name: Barak
    image: /local/custom_ui/floorplan/floorplan.svg
    stylesheet: /local/custom_ui/floorplan/floorplan.css
    date_format: DD.MMM.YYYY
