- alias: 'Main door opened'
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00016d6ddb 
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_34ce0088d9ad
        brightness: 50
        color_name: lightgoldenrodyellow
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: 34ce0088d9ad 
        ringtone_id: 12
        ringtone_vol: 5 

- alias: 'Main door closed'
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00016d6ddb 
      to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.gateway_light_34ce0088d9ad

- alias: 'Main door left opened'
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00016d6ddb 
      to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.door_window_sensor_158d00016d6ddb 
    state: 'on'
    for:
      minutes: 2
  action:
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_34ce0088d9ad
        brightness: 50
        color_name: lightgoldenrodyellow
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: 34ce0088d9ad 
        ringtone_id: 10
        ringtone_vol: 50

