- alias: 'Living room fan On - temperature ascending'
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_temperature_ascending 
      to: 'on'
  condition:
    condition: numeric_state
    entity_id: sensor.temperature_158d0001a4b947
    below: 25
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.stoves_fan

- alias: 'Living room fan Off - temperature ascending'
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_temperature_ascending 
      to: 'off'
  condition:
    condition: numeric_state
    entity_id: sensor.temperature_158d0001a4b947
    below: 23
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.stoves_fan

- alias: 'Living room fan Off - temperature above 25°C'
  initial_state: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperature_158d0001a4b947
      above: 25
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.stoves_fan
