- alias: 'Living room is cold'
  initial_state: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperature_158d0001a4b947 
      below: 21
  condition:
    - condition: time
      after: '07:00:00'
      before: '22:00:00'  
  action:
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_34ce0088d9ad
        color_name: red
        brightness: 50

- alias: 'Living room is not cold'
  initial_state: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperature_158d0001a4b947
      above: 21
  action:
    - service: light.turn_off
      data:
        entity_id: light.gateway_light_34ce0088d9ad

