- alias: 'Living room fan On - temperature ascending'
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_temperature_ascending 
      to: 'on'
    - platform: numeric_state
      entity_id: sensor.temperature_158d0001a4b947 
      below: 25
  condition:
    condition: numeric_state
    entity_id: sensor.temperature_158d0001a4b947
    below: 25
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.stoves_fan

- alias: 'Living room fan Off - low/high temperature°C'
  initial_state: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperature_158d0001a4b947 
      below: 17
    - platform: numeric_state
      entity_id: sensor.temperature_158d0001a4b947 
      below: 18
    - platform: numeric_state
      entity_id: sensor.temperature_158d0001a4b947 
      below: 19
    - platform: numeric_state
      entity_id: sensor.temperature_158d0001a4b947 
      below: 20
    - platform: numeric_state
      entity_id: sensor.temperature_158d0001a4b947 
      below: 20.5
    - platform: numeric_state
      entity_id: sensor.temperature_158d0001a4b947 
      above: 25
    - platform: state
      entity_id: binary_sensor.livingroom_temperature_ascending 
      to: 'off'
  condition:
      condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.temperature_158d0001a4b947
          above: 25
        - condition: numeric_state
          entity_id: sensor.temperature_158d0001a4b947
          below: 22
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.stoves_fan
