- alias: 'Babyphone MiFang2 on'
  trigger:
    platform: state
    entity_id: input_boolean.babyphone_mifang2
    from: 'off'
    to: 'on'
  action:
    - service: ffmpeg.start
      entity_id: binary_sensor.ffmpeg_noise_miFang2
    - service: notify.messenger
      data:
        message: 'Baby monitor MiFang2 on'
        target:
          - '+420777148912'
          - '+420605728246'
          
- alias: 'Babyphone MiFang2 Alert'
  trigger:
    platform: state
    entity_id: binary_sensor.ffmpeg_noise_miFang2
    from: 'off'
    to: 'on'
  action:
    - service: notify.messenger
      data:
        message: 'Baby monitor MiFang2 Alert!'
        target:
          - '+420777148912'
          - '+420605728246'

- alias: 'Babyphone MiFang2 off'
  trigger:
    platform: state
    entity_id: input_boolean.babyphone_mifang2
    from: 'on'
    to: 'off'
  action:
    - service: ffmpeg.stop
      entity_id: binary_sensor.ffmpeg_noise_miFang2
    - service: notify.messenger
      data:
        message: 'Baby monitor MiFang2 off'
        target:
          - '+420777148912'
          - '+420605728246'