- alias: Notify Temp Compare Warmer Outside
  trigger:
    platform: state
    entity_id: sensor.outside_vs_inside_temp
    to: 'Warmer Outside'
  action:
    service: notify.messenger
    data:
      message: 'Outside is warmer than inside. Close all windows!!!' 
      target:
        - '+420777148912'
        - '+420605728246'

- alias: Notify Temp Compare Cooler Outside
  trigger:
    platform: state
    entity_id: sensor.outside_vs_inside_temp
    to: 'Cooler Outside'
  action:
    service: notify.messenger
    data:
      message: 'Outside is colder than inside, it is safe to open windows.'
      target:
        - '+420777148912'
        - '+420605728246'