- alias: 'Clara thermostat on'
  initial_state: True
  trigger:
    - platform: state
      entity_id: input_boolean.clara_heater 
      to: 'on'
    - platform: time
      minutes: '/2'
      seconds: 00
  condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.clara_heater
          state: 'on'
        - condition: state
          entity_id: sensor.bedroom_thermostat_hvac_state
          state: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.bedroom
        temperature: >
          {% if (states.sensor.bedroom_thermostat_target.state | float) < 23 %}
            {{ 1 + (states.sensor.bedroom_thermostat_target.state | float) }}
          {% else %}
            23
          {% endif %}
          
- alias: 'Clara thermostat off'
  initial_state: True
  trigger:
    - platform: state
      entity_id: input_boolean.clara_heater 
      to: 'off'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.bedroom
        temperature: >
          {% if states.climate.bedroom_reference.attributes.temperature %}
            {{ (states.climate.bedroom_reference.attributes.temperature | float) }}
          {% else %}
            21
          {% endif %}
          
- alias: 'Clara thermostat activate'
  initial_state: True
  trigger:
    - platform: time
      hours: 20
      minutes: 00
      seconds: 00
  action:
    - service: climate.set_operation_mode
      data_template:
        entity_id: climate.clara
        operation_mode: "heat"
        
- alias: 'Clara thermostat deactivate'
  initial_state: True
  trigger:
    - platform: time
      hours: 8
      minutes: 00
      seconds: 00
  action:
    - service: climate.set_operation_mode
      data_template:
        entity_id: climate.clara
        operation_mode: "off"