secondary_thermostats:
  name: Secondary thermostats active
  initial: on  
 
clara_heater:
  name: Clara's room heating
  initial: off
    
bedroom_heater:
  name: Bedroom heating
  initial: off