entities:
  - name: Router
    url: http://192.168.1.1/
    icon: mdi:router-wireless
  - name: Home Assistant
    url: https://home-assistant.io
    icon: mdi:home-assistant
  - name: Material Design Icons
    url: https://materialdesignicons.com/
    icon: mdi:material-ui
