entities:
  - name: TpLink Archer C5
    url: http://192.168.1.1/
    icon: mdi:router-wireless
  - name: LEDE - Archer C5 - detail
    url: https://lede-project.org/toh/hwdata/tp-link/tp-link_archer_c5_ac1200_v2.0
    icon: mdi:router-wireless
  - name: Home Assistant
    url: https://home-assistant.io
  - name: Home Assistant - Change Log
    url: https://github.com/home-assistant/home-assistant/releases
    icon: mdi:home-assistant
  - name: Material Design Icons
    url: https://materialdesignicons.com/
    icon: mdi:material-ui
