#view: yes
name: Bathroom 2nd floor
entities:
  - sensor.temperature_158d0001a4b87c
  - sensor.humidity_158d0001a4b87c
  - sensor.pressure_158d0001a4b87c
  - sensor.bathroom_2nd_room_mold
  - binary_sensor.door_window_sensor_158d0001a65c01