#view: yes
name: Bedroom
entities:
  - sensor.temperature_158d0001a4a4e9
  - sensor.humidity_158d0001a4a4e9
  - sensor.pressure_158d0001a4a4e9
  - sensor.bedroom_mold
  - sensor.pushbullet_title
  - sensor.pushbullet_body
  - binary_sensor.bedroom_thermostat_online
  - binary_sensor.bedroom_thermostat_fan
  - binary_sensor.bedroom_thermostat_has_leaf
  - binary_sensor.bedroom_thermostat_is_locked
  - binary_sensor.bedroom_thermostat_is_using_emergency_heat
  - sensor.bedroom_thermostat_humidity
  - sensor.bedroom_thermostat_hvac_state
  - sensor.bedroom_thermostat_operation_mode
  - sensor.bedroom_thermostat_target
  - sensor.bedroom_thermostat_temperature
  - climate.bedroom
  - climate.bedroom_reference
  - media_player.kodi_bedroom
  - group.mifang1_babymonitor