#view: yes
name: Clara's room
entities:
  - sensor.temperature_158d0001a4c566
  - sensor.humidity_158d0001a4c566
  - sensor.pressure_158d0001a4c566
  - sensor.clara_room_mold
  - climate.clara
  - automation.clara_thermostat_on
  - automation.clara_thermostat_off
  - automation.clara_thermostat_activate
  - automation.clara_thermostat_deactivate