#view: yes
name: Coffee room
entities:
  - sensor.temperature_158d0001a253a0
  - sensor.humidity_158d0001a253a0
  - sensor.pressure_158d0001a253a0
  - binary_sensor.door_window_sensor_158d0001a65c5f  
  - automation.coffee_room_door_opened
  - automation.coffee_room_door_closed
  - automation.coffee_room_door_left_opened 