name: Cradle  
entities:
  - input_number.cradle_strip_speed  
  - input_number.cradle_brightness_slider
  - light.cradle_led
  - sensor.cradle_pir
  # - automation.notifikace_telegram
  # - automation.notifikace_gmail
  - input_number.cradle_timer_slider
  - automation.cradle_auto_on
  - automation.cradle_auto_off
  - automation.cradle_effect_speed
  - timer.cradle_timer