#view: yes
name: Grandpa's room
entities:
  - sensor.temperature_158d0001a4a4f3
  - sensor.humidity_158d0001a4a4f3
  - sensor.pressure_158d0001a4a4f3
  - sensor.grandpass_room_mold
  - sensor.outside_vs_inside_temp