view: yes
entities:
  - binary_sensor.door_window_sensor_158d00016d6ddb
  - binary_sensor.door_window_sensor_158d0001a3e0f4
  - sensor.temperature_158d0001a4b95b
  - sensor.humidity_158d0001a4b95b
  - sensor.pressure_158d0001a4b95b