#view: yes
name: Living room
entities:
  - sensor.temperature_158d0001a4b947
  - sensor.humidity_158d0001a4b947
  - sensor.pressure_158d0001a4b947
  - sensor.living_room_mold
  - sensor.illumination_34ce0088d9ad
  - light.gateway_light_34ce0088d9ad
  - group.stove_fan
  - binary_sensor.smoke_sensor_158d0001b8a531