#view: yes
name: Living room
entities:
  - sensor.temperature_158d0001a4b947
  - sensor.humidity_158d0001a4b947
  - sensor.pressure_158d0001a4b947
  - sensor.living_room_mold
  - sensor.illumination_34ce0088d9ad
  - light.gateway_light_34ce0088d9ad
  - sensor.stoves_fan_energy  
  - sensor.stoves_fan_power
  - sensor.stoves_fan_today_power
  - sensor.stoves_fan_yesterday_power  
  - sensor.stoves_fan_total_power
  - sensor.stoves_fan_voltage
  - sensor.stoves_fan_current  
  - switch.stoves_fan 
  - switch.stoves_fan_state
  - binary_sensor.livingroom_temperature_ascending
  - automation.living_room_fan_on__temperature_ascending
  - automation.living_room_fan_off__lowhigh_temperaturec
  - automation.living_room_is_not_cold
  - automation.living_room_is_cold
  - binary_sensor.smoke_sensor_158d0001b8a531