name: People
entities:
  - device_tracker.Honza_LeEco
  - device_tracker.Honza_AmazFit
  - device_tracker.Galca_LeEco
  - device_tracker.Galina
  - device_tracker.Galina2
  - device_tracker.Galina3
  - device_tracker.Lubos
  - device_tracker.Dusan
  - device_tracker.Hela
