#view: yes
name: Spare room
entities:
  - sensor.temperature_158d0001720046
  - sensor.humidity_158d0001720046
  - sensor.pressure_158d0001720046
  - sensor.spare_room_mold
  - vacuum.xiaomi_vacuum
  - group.mifang2_babymonitor  