name: Unknown devices
entities:
  - device_tracker.00133b101b3f
  - device_tracker.307512e78775
  - device_tracker.b4e1c4d0e5f8
  - device_tracker.00156dd2bdcb
  - device_tracker.e498d14a4c1c
  - device_tracker.68071515dac4
  - device_tracker.a628f5d539c5
  - device_tracker.6805ca3ec341