name: Upstairs
view: yes
entities:
  - group.bedroom_room
  - group.outside
  - group.bathroom_2nd_floor
  - group.clarass_room
  - group.grandpas_room
  - group.cradle
#  - group.mifang1_babymonitor
