project_id: !secret google_assistant.project_id
client_id: !secret google_assistant.client_id
access_token: !secret google_assistant.access_token
agent_user_id: !secret google_assistant.agent_user_id
api_key: !secret google_assistant.api_key
#exposed_domains:
#  - switch
#  - light
#  - group
# entity_config:
  # switch.kitchen:
    # name: Custom Name for Google Assistant
    # aliases:
      # - bright lights
      # - entry lights
  # light.living_room:
    # expose: false
    # room: living room