# Name of the location where Home Assistant is running
name: !secret name 
# Location required to calculate the time the sun rises and sets
latitude: !secret latitude 
longitude: !secret longitude
# Impacts weather/sunrise data (altitude above sea level in meters)
elevation: !secret elevation
# metric for Metric, imperial for Imperial
unit_system: metric
# Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
time_zone: !secret time_zone 
customize: !include_dir_merge_named ../customizations

packages: 
    pack_1: !include ../../config/packages/bedLedStrip.yaml
    pack_2: !include ../../config/packages/cradleLedStrip.yaml
