- platform: mqtt_json
  name: "Cradle LED"
  state_topic: "cradle/led"
  command_topic: "cradle/led/set"
  effect: true
  effect_list:
    - bpm
    - candy cane  
    - confetti  
    - cyclon rainbow  
    - dots  
    - fire  
    - glitter  
    - juggle  
    - lightning
    - noise  
    - police all  
    - police one  
    - rainbow  
    - rainbow with glitter  
    - ripple  
    - sinelon  
    - solid  
    - twinkle  
  brightness: true
  flash: true
  rgb: true
  optimistic: false
  qos: 1
 