- platform: !secret device_tracker_platform 
  host: !secret device_tracker_host
  username: !secret device_tracker_username
  password: !secret device_tracker_password
  confider_home: 180
  track_new_devices: yes
