- platform: kodi
  host: 192.168.1.152
  port: 8080
  name: Kodi bedroom
  enable_websocket: true
#- platform: spotify
#  client_id: !secret spotify.client_id
#  client_secret: !secret spotify.client_secret
  #aliases:
  #    abc123def456: 'Living Room'
  #    9183abas000: 'Bed Room'